spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: boat
  session:
    store-type: none
  datasource:
    url: "jdbc:postgresql://postgres-boat:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}